version: '3'
services:
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
      - "./proxy/conf.d:/etc/nginx/conf.d"
    ports:
      - "${PROXY_HTTP_PORT}:${PROXY_HTTP_PORT}"
      - "${PROXY_HTTPS_PORT}:${PROXY_HTTPS_PORT}"
